ADD KMS CMEK encryption option for GCS bucket creation
ofek/csi-gcs pull request #59
Opened 2021-01-12 07:41 UTC by hayorov

- Add an option to create GCP buckets with KMS /CMEK encryption option
- Pre-created KMS key is required
- Default is the same (no encryption)
- Minor go version and fmt updates

2021-01-12 11:13 UTC, maennchen requested changes

2021-01-12 11:13 UTC, maennchen commented on deploy/overlays/stable/kustomization.yaml
> -  newTag: v0.5.0
I would prefer to do the release in a separate commit.

2021-01-12 11:14 UTC, maennchen commented
@hayorov Thanks a lot for your contribution.

I'd like to await a review from @ofek as well, in my own opinion it looks good.

2021-01-12 14:04 UTC, ofek requested changes
@hayorov Great job, thanks!

Let's remove the version bump as @maennchen suggested, then I'll merge.

2021-01-13 02:16 UTC, hayorov commented
Many thanks, @maennchen, @ofek.

Updated according to comments.

2021-01-13 02:54 UTC, ofek approved these changes
@maennchen Do you mind releasing?

2021-01-13 02:54 UTC, merged

2021-01-13 10:50 UTC, maennchen commented
@ofek It's released. There's a problem though with the release of the docs: https://github.com/ofek/csi-gcs/issues/62